// MOSSVEIL — shaders.js : node-based shader graph -> fullscreen screen-effect overlay (G.Shaders).
// Roadmap #78. NET-NEW render feature & the FIRST authorable GLSL surface in the project.
//
// A "graph" is a little DAG of typed nodes (sources · generators · math · colour · output). Each node
// type knows how to emit BOTH a GLSL expression AND an equivalent CPU (JS) value, so:
//   • the editor previews the graph on the CPU (no second WebGL context — exactly like the parallax /
//     decals tools), and
//   • the game compiles the SAME graph to a fragment shader and draws it as a transparent FULLSCREEN
//     overlay composited on top of the final frame (animated fog, scanlines, pulsing vignettes, colour
//     washes…). Blend (normal/additive) and opacity are per-graph.
//
// Graphs are authored in data/shaders.js (G.SHADERS_DATA). `active` names the one graph applied in
// game ('' = none → the overlay does NOTHING and the frame is byte-identical to before this feature).
// The single game seam is one guarded `G.Shaders.renderOverlay(dt)` after the post pass. No THREE /
// document at LOAD time (gen-data node-evals this for the default overlay); every node's GLSL is
// generated by a small compiler so it ALWAYS type-checks (floats and vec3s auto-convert), and material
// creation is try/caught so a bad graph can never crash the renderer.
(function () {
  const S = G.Shaders = {};
  const clone = o => JSON.parse(JSON.stringify(o));
  const num = (v, d) => (typeof v === 'number' && isFinite(v)) ? v : d;
  const clamp = (v, lo, hi, d) => Math.max(lo, Math.min(hi, num(v, d)));
  const TAU = Math.PI * 2;

  // ============================================================ GLSL formatting helpers
  function glf(n) { n = +n; if (!isFinite(n)) n = 0; let s = '' + n; if (!/[.eE]/.test(s)) s += '.0'; return s; }
  function gli(n) { return '' + (n | 0); }

  // ============================================================ node registry
  // Each node: { label, cat, ret:'float'|'vec3'|'out', ins:[portNames], props:{key:[def,min,max,int?]},
  //              glsl(p, IN), cpu(p, IN, ctx) }  where IN[port] is { v, ret } (glsl) or a value (cpu).
  // asF / asV auto-convert between float and vec3 so any wire is legal; a missing input uses `dflt`.
  function asF(e, d) { if (!e) return glf(d); return e.ret === 'vec3' ? '_lum(' + e.v + ')' : e.v; }
  function asV(e, d) { if (!e) return 'vec3(' + glf(d) + ')'; return e.ret === 'float' ? 'vec3(' + e.v + ')' : e.v; }
  function cF(v, d) { if (v == null) return d; return Array.isArray(v) ? (0.299 * v[0] + 0.587 * v[1] + 0.114 * v[2]) : v; }
  function cV(v, d) { if (v == null) return [d, d, d]; return Array.isArray(v) ? v : [v, v, v]; }
  const cl01 = x => Math.max(0, Math.min(1, x));
  const sstep = (a, b, x) => { if (a === b) return x < a ? 0 : 1; const t = cl01((x - a) / (b - a)); return t * t * (3 - 2 * t); };

  // CPU procedural noise (visually mirrors the GLSL prelude; need not be bit-identical)
  function jhash(x, y) { const s = Math.sin(x * 127.1 + y * 311.7) * 43758.5453123; return s - Math.floor(s); }
  function jnoise(x, y) {
    const ix = Math.floor(x), iy = Math.floor(y), fx = x - ix, fy = y - iy;
    const a = jhash(ix, iy), b = jhash(ix + 1, iy), c = jhash(ix, iy + 1), d = jhash(ix + 1, iy + 1);
    const ux = fx * fx * (3 - 2 * fx), uy = fy * fy * (3 - 2 * fy);
    return a * (1 - ux) * (1 - uy) + b * ux * (1 - uy) + c * (1 - ux) * uy + d * ux * uy;
  }
  function jfbm(x, y, oct) { let s = 0, a = 0.5; for (let i = 0; i < oct; i++) { s += a * jnoise(x, y); x *= 2; y *= 2; a *= 0.5; } return s; }
  function jvoro(x, y) {
    const gx = Math.floor(x), gy = Math.floor(y), fx = x - gx, fy = y - gy; let md = 1.5;
    for (let oy = -1; oy <= 1; oy++) for (let ox = -1; ox <= 1; ox++) {
      const rx = ox + jhash(gx + ox, gy + oy) - fx, ry = oy + jhash(gx + ox + 7, gy + oy + 3) - fy;
      md = Math.min(md, rx * rx + ry * ry);
    }
    return cl01(Math.sqrt(md));
  }

  const NODES = {
    // ---- sources ----
    uvx:   { label: 'UV.x', cat: 'Source', ret: 'float', ins: [], props: {}, glsl: () => 'vUv.x', cpu: (p, I, c) => c.x },
    uvy:   { label: 'UV.y', cat: 'Source', ret: 'float', ins: [], props: {}, glsl: () => 'vUv.y', cpu: (p, I, c) => c.y },
    time:  { label: 'Time', cat: 'Source', ret: 'float', ins: [], props: { speed: [1, -10, 10] }, glsl: p => '(uTime*' + glf(p.speed) + ')', cpu: (p, I, c) => c.t * p.speed },
    const: { label: 'Const', cat: 'Source', ret: 'float', ins: [], props: { value: [0.5, -100, 100] }, glsl: p => glf(p.value), cpu: p => p.value },
    color: { label: 'Colour', cat: 'Source', ret: 'vec3', ins: [], props: { r: [1, 0, 1], g: [1, 0, 1], b: [1, 0, 1] }, glsl: p => 'vec3(' + glf(p.r) + ',' + glf(p.g) + ',' + glf(p.b) + ')', cpu: p => [p.r, p.g, p.b] },

    // ---- generators (use uv internally, output 0..1) ----
    linear:  { label: 'Linear ramp', cat: 'Generator', ret: 'float', ins: [], props: { angle: [0, -7, 7] },
      glsl: p => 'clamp(dot(vUv-0.5, vec2(cos(' + glf(p.angle) + '),sin(' + glf(p.angle) + ')))+0.5, 0.0, 1.0)',
      cpu: (p, I, c) => cl01((c.x - 0.5) * Math.cos(p.angle) + (c.y - 0.5) * Math.sin(p.angle) + 0.5) },
    radial:  { label: 'Radial', cat: 'Generator', ret: 'float', ins: [], props: { cx: [0.5, 0, 1], cy: [0.5, 0, 1], scale: [1, 0.01, 8] },
      glsl: p => 'clamp(length(vUv-vec2(' + glf(p.cx) + ',' + glf(p.cy) + '))*2.0*' + glf(p.scale) + ', 0.0, 1.0)',
      cpu: (p, I, c) => cl01(Math.hypot(c.x - p.cx, c.y - p.cy) * 2 * p.scale) },
    wave:    { label: 'Wave', cat: 'Generator', ret: 'float', ins: [], props: { axis: [0, 0, 1, 1], freq: [8, 0, 512], speed: [1, -40, 40], phase: [0, -7, 7] },
      glsl: p => '(0.5+0.5*sin((' + (p.axis ? 'vUv.y' : 'vUv.x') + ')*' + glf(p.freq) + '*6.2831853 + uTime*' + glf(p.speed) + ' + ' + glf(p.phase) + '))',
      cpu: (p, I, c) => 0.5 + 0.5 * Math.sin((p.axis ? c.y : c.x) * p.freq * TAU + c.t * p.speed + p.phase) },
    rings:   { label: 'Rings', cat: 'Generator', ret: 'float', ins: [], props: { cx: [0.5, 0, 1], cy: [0.5, 0, 1], freq: [8, 0, 256], speed: [0, -40, 40] },
      glsl: p => '(0.5+0.5*sin(length(vUv-vec2(' + glf(p.cx) + ',' + glf(p.cy) + '))*' + glf(p.freq) + '*6.2831853 - uTime*' + glf(p.speed) + '))',
      cpu: (p, I, c) => 0.5 + 0.5 * Math.sin(Math.hypot(c.x - p.cx, c.y - p.cy) * p.freq * TAU - c.t * p.speed) },
    noise:   { label: 'Noise', cat: 'Generator', ret: 'float', ins: [], props: { scale: [6, 0.1, 128], speed: [0, -20, 20] },
      glsl: p => '_vnoise(vUv*' + glf(p.scale) + ' + uTime*' + glf(p.speed) + ')',
      cpu: (p, I, c) => jnoise(c.x * p.scale + c.t * p.speed, c.y * p.scale) },
    fbm:     { label: 'FBM (clouds)', cat: 'Generator', ret: 'float', ins: [], props: { scale: [4, 0.1, 64], octaves: [4, 1, 6, 1], speed: [0, -20, 20] },
      glsl: p => '_fbm(vUv*' + glf(p.scale) + ' + uTime*' + glf(p.speed) + ', ' + gli(p.octaves) + ')',
      cpu: (p, I, c) => jfbm(c.x * p.scale + c.t * p.speed, c.y * p.scale, p.octaves) },
    voronoi: { label: 'Voronoi', cat: 'Generator', ret: 'float', ins: [], props: { scale: [6, 0.1, 128], speed: [0, -20, 20] },
      glsl: p => '_voro(vUv*' + glf(p.scale) + ' + uTime*' + glf(p.speed) + ')',
      cpu: (p, I, c) => jvoro(c.x * p.scale + c.t * p.speed, c.y * p.scale) },

    // ---- math (float in/out) ----
    add:      { label: 'Add', cat: 'Math', ret: 'float', ins: ['a', 'b'], props: { bias: [0, -10, 10] }, glsl: (p, I) => '(' + asF(I.a, 0) + '+' + asF(I.b, 0) + '+' + glf(p.bias) + ')', cpu: (p, I) => cF(I.a, 0) + cF(I.b, 0) + p.bias },
    mul:      { label: 'Multiply', cat: 'Math', ret: 'float', ins: ['a', 'b'], props: { gain: [1, -10, 10] }, glsl: (p, I) => '(' + asF(I.a, 1) + '*' + asF(I.b, 1) + '*' + glf(p.gain) + ')', cpu: (p, I) => cF(I.a, 1) * cF(I.b, 1) * p.gain },
    mix:      { label: 'Mix', cat: 'Math', ret: 'float', ins: ['a', 'b', 't'], props: {}, glsl: (p, I) => 'mix(' + asF(I.a, 0) + ',' + asF(I.b, 1) + ', clamp(' + asF(I.t, 0.5) + ',0.0,1.0))', cpu: (p, I) => { const t = cl01(cF(I.t, 0.5)); return cF(I.a, 0) * (1 - t) + cF(I.b, 1) * t; } },
    pow:      { label: 'Power', cat: 'Math', ret: 'float', ins: ['a'], props: { e: [2, 0.01, 16] }, glsl: (p, I) => 'pow(max(' + asF(I.a, 0) + ',0.0), ' + glf(p.e) + ')', cpu: (p, I) => Math.pow(Math.max(0, cF(I.a, 0)), p.e) },
    sine:     { label: 'Sine', cat: 'Math', ret: 'float', ins: ['a'], props: { freq: [6.2832, -64, 64], phase: [0, -7, 7] }, glsl: (p, I) => '(0.5+0.5*sin(' + asF(I.a, 0) + '*' + glf(p.freq) + ' + ' + glf(p.phase) + '))', cpu: (p, I) => 0.5 + 0.5 * Math.sin(cF(I.a, 0) * p.freq + p.phase) },
    absn:     { label: 'Abs', cat: 'Math', ret: 'float', ins: ['a'], props: {}, glsl: (p, I) => 'abs(' + asF(I.a, 0) + ')', cpu: (p, I) => Math.abs(cF(I.a, 0)) },
    oneminus: { label: 'One minus', cat: 'Math', ret: 'float', ins: ['a'], props: {}, glsl: (p, I) => '(1.0-' + asF(I.a, 0) + ')', cpu: (p, I) => 1 - cF(I.a, 0) },
    smooth:   { label: 'Smoothstep', cat: 'Math', ret: 'float', ins: ['a'], props: { e0: [0, -2, 2], e1: [1, -2, 2] }, glsl: (p, I) => 'smoothstep(' + glf(p.e0) + ',' + glf(p.e1) + ',' + asF(I.a, 0) + ')', cpu: (p, I) => sstep(p.e0, p.e1, cF(I.a, 0)) },
    clamp01:  { label: 'Clamp 0–1', cat: 'Math', ret: 'float', ins: ['a'], props: {}, glsl: (p, I) => 'clamp(' + asF(I.a, 0) + ',0.0,1.0)', cpu: (p, I) => cl01(cF(I.a, 0)) },

    // ---- colour (vec3 out) ----
    colorize: { label: 'Colorize', cat: 'Colour', ret: 'vec3', ins: ['t'], props: { r0: [0, 0, 1], g0: [0, 0, 1], b0: [0, 0, 1], r1: [1, 0, 1], g1: [1, 0, 1], b1: [1, 0, 1] },
      glsl: (p, I) => 'mix(vec3(' + glf(p.r0) + ',' + glf(p.g0) + ',' + glf(p.b0) + '), vec3(' + glf(p.r1) + ',' + glf(p.g1) + ',' + glf(p.b1) + '), clamp(' + asF(I.t, 0) + ',0.0,1.0))',
      cpu: (p, I) => { const t = cl01(cF(I.t, 0)); return [p.r0 + (p.r1 - p.r0) * t, p.g0 + (p.g1 - p.g0) * t, p.b0 + (p.b1 - p.b0) * t]; } },
    tint:     { label: 'Tint', cat: 'Colour', ret: 'vec3', ins: ['col'], props: { r: [1, 0, 2], g: [1, 0, 2], b: [1, 0, 2] },
      glsl: (p, I) => '(' + asV(I.col, 1) + ' * vec3(' + glf(p.r) + ',' + glf(p.g) + ',' + glf(p.b) + '))',
      cpu: (p, I) => { const v = cV(I.col, 1); return [v[0] * p.r, v[1] * p.g, v[2] * p.b]; } },
    mixcol:   { label: 'Mix colours', cat: 'Colour', ret: 'vec3', ins: ['a', 'b', 't'], props: {},
      glsl: (p, I) => 'mix(' + asV(I.a, 0) + ',' + asV(I.b, 1) + ', clamp(' + asF(I.t, 0.5) + ',0.0,1.0))',
      cpu: (p, I) => { const t = cl01(cF(I.t, 0.5)), a = cV(I.a, 0), b = cV(I.b, 1); return [a[0] + (b[0] - a[0]) * t, a[1] + (b[1] - a[1]) * t, a[2] + (b[2] - a[2]) * t]; } },

    // ---- output ----
    output: { label: 'Output', cat: 'Output', ret: 'out', ins: ['rgb', 'alpha'], props: {},
      glsl: (p, I) => 'gl_FragColor = vec4(' + asV(I.rgb, 0) + ', clamp(' + asF(I.alpha, 1) + ',0.0,1.0) * uOpacity);',
      cpu: (p, I) => { const v = cV(I.rgb, 0); return { r: v[0], g: v[1], b: v[2], a: cl01(cF(I.alpha, 1)) }; } }
  };
  const TYPES = Object.keys(NODES);

  // ============================================================ defaults (authored CLEAN: props in
  // registry order, within range, so a default overlay round-trips byte-identical). active:'' so the
  // overlay is OFF by default and the frame is unchanged.
  const DEFAULTS = {
    enabled: true,
    active: '',
    graphs: {
      'vignette-pulse': {
        name: 'Vignette pulse', blend: 'normal', opacity: 1, out: 'out',
        nodes: {
          r1:  { type: 'radial', x: 40,  y: 40,  props: { cx: 0.5, cy: 0.5, scale: 1 }, ins: {} },
          e1:  { type: 'smooth', x: 250, y: 40,  props: { e0: 0.45, e1: 1 }, ins: { a: 'r1' } },
          tm:  { type: 'time',   x: 40,  y: 180, props: { speed: 1.5 }, ins: {} },
          pl:  { type: 'sine',   x: 250, y: 180, props: { freq: 1, phase: 0 }, ins: { a: 'tm' } },
          am:  { type: 'mul',    x: 460, y: 110, props: { gain: 0.55 }, ins: { a: 'e1', b: 'pl' } },
          col: { type: 'color',  x: 460, y: 260, props: { r: 0.02, g: 0, b: 0.05 }, ins: {} },
          out: { type: 'output', x: 680, y: 180, props: {}, ins: { rgb: 'col', alpha: 'am' } }
        }
      },
      'scanlines': {
        name: 'Scanlines', blend: 'normal', opacity: 1, out: 'out',
        nodes: {
          w1:  { type: 'wave',     x: 40,  y: 60,  props: { axis: 1, freq: 140, speed: 0, phase: 0 }, ins: {} },
          om:  { type: 'oneminus', x: 260, y: 60,  props: {}, ins: { a: 'w1' } },
          am:  { type: 'mul',      x: 460, y: 60,  props: { gain: 0.16 }, ins: { a: 'om', b: 'om' } },
          col: { type: 'color',    x: 260, y: 220, props: { r: 0, g: 0, b: 0 }, ins: {} },
          out: { type: 'output',   x: 680, y: 140, props: {}, ins: { rgb: 'col', alpha: 'am' } }
        }
      },
      'dream-fog': {
        name: 'Dream fog', blend: 'additive', opacity: 1, out: 'out',
        nodes: {
          f1:  { type: 'fbm',      x: 40,  y: 60,  props: { scale: 3, octaves: 4, speed: 0.05 }, ins: {} },
          cz:  { type: 'colorize', x: 280, y: 40,  props: { r0: 0.08, g0: 0.16, b0: 0.2, r1: 0.5, g1: 0.78, b1: 0.85 }, ins: { t: 'f1' } },
          am:  { type: 'mul',      x: 280, y: 230, props: { gain: 0.22 }, ins: { a: 'f1', b: 'f1' } },
          out: { type: 'output',   x: 560, y: 130, props: {}, ins: { rgb: 'cz', alpha: 'am' } }
        }
      }
    }
  };

  // ============================================================ data layer (validate + byte-identical)
  let cfg = null;
  function cleanProps(type, props) {
    const spec = NODES[type], out = {};
    for (const key in spec.props) { const ps = spec.props[key]; let v = clamp(props && props[key], ps[1], ps[2], ps[0]); if (ps[3]) v = Math.round(v); out[key] = v; }
    return out;
  }
  function cleanIns(type, ins) {
    const spec = NODES[type], out = {};
    for (const port of spec.ins) { const v = ins && ins[port]; out[port] = (typeof v === 'string') ? v : null; }
    return out;
  }
  function cleanNode(n) {
    if (!n || !NODES[n.type]) return null;                      // drop unknown node types
    return { type: n.type, x: num(n.x, 0) | 0, y: num(n.y, 0) | 0, props: cleanProps(n.type, n.props), ins: cleanIns(n.type, n.ins) };
  }
  function cleanGraph(g) {
    const src = (g && g.nodes && typeof g.nodes === 'object') ? g.nodes : {};
    const nodes = {};
    for (const id in src) { const cn = cleanNode(src[id]); if (cn) nodes[id] = cn; }
    return {
      name: (g && typeof g.name === 'string') ? g.name : 'Graph',
      blend: (g && g.blend === 'additive') ? 'additive' : 'normal',
      opacity: clamp(g && g.opacity, 0, 1, 1),
      out: (g && typeof g.out === 'string' && nodes[g.out]) ? g.out : null,
      nodes
    };
  }
  function applyData(data) {
    const d = data || (typeof G !== 'undefined' && G.SHADERS_DATA) || null;
    cfg = clone(DEFAULTS);
    if (d) {
      cfg.enabled = d.enabled !== false;
      cfg.active = (typeof d.active === 'string') ? d.active : '';
      if (d.graphs && typeof d.graphs === 'object') {
        cfg.graphs = {};
        for (const id in d.graphs) cfg.graphs[id] = cleanGraph(d.graphs[id]);
      }
    }
    built = null;   // any active material is now stale
  }
  S.applyData = applyData;
  S.exportDefaults = () => clone(DEFAULTS);
  S.exportCurrent = () => clone(cfg);
  S.cleanGraph = g => cleanGraph(g);
  S.cleanNode = n => cleanNode(n);
  S.NODE_TYPES = () => TYPES.slice();
  S.nodeMeta = () => TYPES.map(t => { const s = NODES[t]; return { type: t, label: s.label, cat: s.cat, ret: s.ret, ins: s.ins.slice(), props: Object.keys(s.props).map(k => ({ key: k, def: s.props[k][0], min: s.props[k][1], max: s.props[k][2], int: !!s.props[k][3] })) }; });
  S.graphs = () => clone(cfg.graphs);
  S.graph = id => cfg.graphs[id] ? clone(cfg.graphs[id]) : null;
  S.active = () => cfg.active;
  S.enabled = () => cfg.enabled;

  // ============================================================ compiler (graph -> GLSL fragment body)
  function compileBody(graph) {
    const nodes = graph.nodes, outId = graph.out;
    const order = [], seen = {};
    (function visit(id, stack) {
      if (!id || !nodes[id] || seen[id] || stack[id]) return;
      stack[id] = 1;
      const spec = NODES[nodes[id].type];
      if (spec) for (const port of spec.ins) visit(nodes[id].ins && nodes[id].ins[port], stack);
      stack[id] = 0; seen[id] = 1; order.push(id);
    })(outId, {});
    let body = '';
    const varOf = {};
    for (const id of order) {
      const n = nodes[id], spec = NODES[n.type]; if (!spec) continue;
      const IN = {};
      for (const port of spec.ins) { const src = n.ins && n.ins[port]; IN[port] = (src && varOf[src]) ? { v: varOf[src], ret: NODES[nodes[src].type].ret } : null; }
      if (spec.ret === 'out') { body += '  ' + spec.glsl(n.props, IN) + '\n'; continue; }
      const v = 'n_' + id.replace(/[^a-zA-Z0-9_]/g, '_');
      varOf[id] = v;
      body += '  ' + (spec.ret === 'vec3' ? 'vec3 ' : 'float ') + v + ' = ' + spec.glsl(n.props, IN) + ';\n';
    }
    // a graph with no reachable output draws nothing (fully transparent)
    if (!nodes[outId] || NODES[nodes[outId].type].ret !== 'out') body += '  gl_FragColor = vec4(0.0);\n';
    return body;
  }
  const VERT = 'varying vec2 vUv; void main(){ vUv = uv; gl_Position = vec4(position.xy, 0.0, 1.0); }';
  const PRELUDE =
    'varying vec2 vUv; uniform float uTime; uniform float uOpacity; uniform vec2 uRes;\n' +
    'float _lum(vec3 c){ return dot(c, vec3(0.299,0.587,0.114)); }\n' +
    'float _hash(vec2 p){ return fract(sin(dot(p, vec2(127.1,311.7)))*43758.5453123); }\n' +
    'float _vnoise(vec2 p){ vec2 i=floor(p), f=fract(p); float a=_hash(i), b=_hash(i+vec2(1.,0.)), c=_hash(i+vec2(0.,1.)), d=_hash(i+vec2(1.,1.)); vec2 u=f*f*(3.-2.*f); return mix(mix(a,b,u.x), mix(c,d,u.x), u.y); }\n' +
    'float _fbm(vec2 p, int oct){ float s=0., a=0.5; for(int i=0;i<6;i++){ if(i>=oct) break; s+=a*_vnoise(p); p*=2.; a*=0.5; } return s; }\n' +
    'float _voro(vec2 p){ vec2 g=floor(p), f=fract(p); float md=1.5; for(int y=-1;y<=1;y++){ for(int x=-1;x<=1;x++){ vec2 o=vec2(float(x),float(y)); vec2 r=o+vec2(_hash(g+o),_hash(g+o+vec2(7.,3.)))-f; md=min(md, dot(r,r)); } } return clamp(sqrt(md),0.,1.); }\n';
  S.glsl = function (graph) { return PRELUDE + 'void main(){\n' + compileBody(graph) + '}\n'; };

  // ============================================================ CPU evaluator (preview & tests)
  S.evalCPU = function (graph, x, y, t) {
    const nodes = graph.nodes, cache = {};
    function ev(id) {
      if (!id || !nodes[id]) return null;
      if (id in cache) return cache[id];
      cache[id] = null;                                          // cycle guard
      const n = nodes[id], spec = NODES[n.type]; if (!spec) return null;
      const IN = {};
      for (const port of spec.ins) IN[port] = ev(n.ins && n.ins[port]);
      return (cache[id] = spec.cpu(n.props, IN, { x: x, y: y, t: t }));
    }
    const o = (graph.out && nodes[graph.out]) ? ev(graph.out) : null;
    return (o && typeof o === 'object' && !Array.isArray(o)) ? o : { r: 0, g: 0, b: 0, a: 0 };
  };

  // ============================================================ in-game fullscreen overlay
  // A private fullscreen quad composited on top of the final frame (after post). Lazy GL; the material
  // is compiled from the active graph and try/caught so a malformed shader can never crash the game.
  let built = null, overScene = null, overCam = null, overQuad = null, geo = null, timeAcc = 0;
  function ensureFS() {
    if (overScene) return true;
    if (typeof THREE === 'undefined' || !G.renderer) return false;
    overScene = new THREE.Scene();
    overCam = new THREE.OrthographicCamera(-1, 1, 1, -1, 0, 1);
    geo = new THREE.PlaneGeometry(2, 2);
    overQuad = new THREE.Mesh(geo, new THREE.MeshBasicMaterial({ visible: false }));
    overQuad.frustumCulled = false;
    overScene.add(overQuad);
    return true;
  }
  function buildMat(graph) {
    return new THREE.ShaderMaterial({
      uniforms: { uTime: { value: 0 }, uOpacity: { value: graph.opacity }, uRes: { value: new THREE.Vector2(1, 1) } },
      vertexShader: VERT, fragmentShader: S.glsl(graph),
      transparent: true, depthTest: false, depthWrite: false,
      blending: graph.blend === 'additive' ? THREE.AdditiveBlending : THREE.NormalBlending
    });
  }
  // the single game seam: composite the active overlay on top of the final frame
  S.renderOverlay = function (dt) {
    if (!cfg || !cfg.enabled || !cfg.active) return;
    const g = cfg.graphs[cfg.active]; if (!g) return;
    if (typeof THREE === 'undefined' || !G.renderer || !ensureFS()) return;
    timeAcc += (dt || 0.016);
    if (!built || built.id !== cfg.active) {
      if (built && built.mat) built.mat.dispose();
      try { const mat = buildMat(g); built = { id: cfg.active, mat: mat }; overQuad.material = mat; }
      catch (e) { built = { id: cfg.active, mat: null, failed: true }; if (console && console.warn) console.warn('Shader graph "' + cfg.active + '" failed to build:', e && e.message); return; }
    }
    if (built.failed || !built.mat) return;
    try {
      const u = built.mat.uniforms;
      u.uTime.value = timeAcc; u.uOpacity.value = g.opacity;
      built.mat.blending = g.blend === 'additive' ? THREE.AdditiveBlending : THREE.NormalBlending;
      const r = G.renderer, sz = r.getSize(new THREE.Vector2());
      u.uRes.value.set(sz.x || 1, sz.y || 1);
      const prevAC = r.autoClear;
      r.setRenderTarget(null); r.autoClear = false; r.render(overScene, overCam); r.autoClear = prevAC;
    } catch (e) { /* never let an overlay error break the frame */ }
  };
  S.invalidate = () => { built = null; };
  S._built = () => built;          // test hook (read-only)

  applyData();
})();
